# Introduction {#intro}

The effects of retinitis pigmentosa (RP) and neurological diseases can simultaneously degrade an animal's behaviors, organs, tissues, and cells. Originating from the disease's loss of function mutations in the retina, electron microscopy images have shown that rod photoreceptor cells die and behavioral studies have shown that animals have difficulty navigating their environment. These observed changes are impactful in guiding treatment development for RP, yet the physiological changes that occur in between rod cell death and night blindness need clarification.  

The retina's role is to encode the specifics of our visual environment through both the quantity and the precise timing of action potentials originating from the ganglion cell layer (GCL). These details are sent through axons in the optic nerve that get transformed by areas of the brain into perceptions that inform an animal's actions. However, RP can obstruct the visual pathway at the stage when Rod photoreceptor cells begin to die. Thus, RP in the retina can affect all steps downstream of the visual pathway by altering signal transmission mechanisms. 

The encoding of visual stimuli by the retina is complex physiologically as it involves representing the spatio-temporal environment into an interpretable train of spikes. Features like the the outline of a baseball and the speed that ball travels after a toss have to be encoded quickly into a batter's retinas. In early studies, action potentials were thought to represent visual stimuli at a time-varying rate, which allowed models to effectively summarize some of the responses of the retina (Adrian 1928). For example, a poison distribution might model the occurrence of spikes pretty easily given this assumption. However, this model assumes that the mean spike count will be equal to the variance of the spike count, which does not agree with the reality of neural responses as they have lower variability than their spike count (Fig A). In addition, certain retinal responses may not be captured by this time-varying rate interpretation as the retina can change its firing rate in a timeframe that is too small to measure the temporal structure of neuronal signals. Studying spike trains using statistical modeling provides insights about retinal response patterns, but also makes mathematical assumptions that do not agree with the particular nature of spike train patterns. 

Instead of studying the firing of spikes by assuming a model, an additional framework to characterize the encoding of retinal responses is also by examining the consistency of the spike trains across repeated trials of the same stimuli. This approach allows taking two directions: estimating the mutual information transmitted about the stimuli and a measure of the spike train distances across the trials. The two approaches differ because the mutual information tries to quantify the total amount of information a neuron or group of neurons sends to the brain about a stimulus. While spike distance metrics try to provide insights about the precision of the neuronal code. These two metrics have utility in studying a disease because they evaluate the retinal code's precision and potential as a disease progresses and after genetic treatment.









